### ISSUE TITLE
When running console without a token the user gets a developer exception

### ISSUE THREAD

**Issue by krainboltgreene** [andrewmcodes/dishwasher#9]
```
𝑓 bin/console
Traceback (most recent call last):
	20: from bin/console:4:in `<main>'
	19: from bin/console:4:in `require'
	18: from /Users/krainboltgreene/Code/krainboltgreene/dishwasher/lib/dishwasher.rb:7:in `<top (required)>'
	17: from /Users/krainboltgreene/Code/krainboltgreene/dishwasher/lib/dishwasher.rb:11:in `<module:Dishwasher>'
	16: from /Users/krainboltgreene/Code/krainboltgreene/dishwasher/lib/dishwasher/github.rb:55:in `choices'
	15: from /Users/krainboltgreene/Code/krainboltgreene/dishwasher/lib/dishwasher/github.rb:46:in `forks'
	14: from /Users/krainboltgreene/Code/krainboltgreene/dishwasher/lib/dishwasher/github.rb:37:in `repos'
	13: from /Users/krainboltgreene/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/client/users.rb:34:in `user'
	12: from /Users/krainboltgreene/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/connection.rb:19:in `get'
	11: from /Users/krainboltgreene/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/connection.rb:156:in `request'
	10: from /Users/krainboltgreene/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	 9: from /Users/krainboltgreene/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/faraday-0.17.0/lib/faraday/connection.rb:138:in `get'
	 8: from /Users/krainboltgreene/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/faraday-0.17.0/lib/faraday/connection.rb:387:in `run_request'
	 7: from /Users/krainboltgreene/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/faraday-0.17.0/lib/faraday/rack_builder.rb:143:in `build_response'
	 6: from /Users/krainboltgreene/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/faraday-0.17.0/lib/faraday/request/retry.rb:130:in `call'
	 5: from /Users/krainboltgreene/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	 4: from /Users/krainboltgreene/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	 3: from /Users/krainboltgreene/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/faraday-0.17.0/lib/faraday/response.rb:8:in `call'
	 2: from /Users/krainboltgreene/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/faraday-0.17.0/lib/faraday/response.rb:61:in `on_complete'
	 1: from /Users/krainboltgreene/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/faraday-0.17.0/lib/faraday/response.rb:9:in `block in call'
/Users/krainboltgreene/.asdf/installs/ruby/2.6.2/lib/ruby/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Requires authentication // See: https://developer.github.com/v3/users/#get-the-authenticated-user (Octokit::Unauthorized)
```

**Comment by andrewmcodes** [comment]
It is now abundantly clear that you need to put in a token.
